# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
#
# This test is meant to verify that our Dockerfile can build successfully when
# changed on the CPU architectures we have made it support being built on.
#
name: Build nfs-ganesha base container

on:
  push: {}

jobs:
  docker:
    name: Build nfs-ganesha base container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Configure QEMU
      uses: docker/setup-qemu-action@v1
    - name: Configure Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./deploy/base/Dockerfile
        tags: ghcr.io/${{ github.repository_owner }}/nfs-provisioner:${{ github.sha }}
        platforms: linux/arm64,linux/amd64
        push: true
